travis:
  secure:
    BINSTAR_TOKEN: Ew7Fn2rwtg6dd1MEMU9ZH5rIEPJzc+4AhKPqigGvth/jgwtHL3J9V2Jw+CIIvOxFNVt3M6rYrYG9W7TmaxPzbKJ+HlPZdq02NC/n/zlT9qZ768gK4Z3Gv/AkQ5uxYbc+uemo0V7593YN3KtKjd/RRkCeJELe7xGmoPeFN3CmOtnXgDrJG475dgfh6a7fXpZAG7M229RxVvqCH2KXg02Wj04rmLbrSSL8qDlV6U36THuW2niV+eL9hJYdBwUKehEPeLTRZp/UgeroxcfR6kRetMOW4LLnp+Knc92RjcSQK5DX7xH+DU1q3urTWfH2r+nn955bwcSkAbfqcbfeMoP5tYT+wm2MeOt5l2gO/wl5GcwkonR9PQfG/MH2b8yrBdEj3sYnXNj9e6QOjhKTi4XsOolB68iv7oq286crv+XbAg3I2+rl0Uj3dqcnsTnEqcn8KzIbnBcTBQibZPTWu7KuxazrBQxEyLDk0UYyFo5QBxzpEjdlB3XQzDZR3NSrCUDF3jnJ1kQXfJRx6UdRlowLTcSonhTkp+jmPEfyhf+SpqQz44Q05ysjJmG2HSD2xMOYCFpU1UePEN/6YP5ZcOQPbfXogCzZD4GatCGePVOcfLfckhxEHCqsO6SSRkqwFsXwm62Dh8J97CPis05AqCeqBWcEVoIM9IR/2oaqswx/M1w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
