travis:
  secure:
    BINSTAR_TOKEN: nBlL954VRF0k6NqNYjxjhbnjptuxvxpEBC7qXGft+ViEVr7QK6S8+ygOXJm7UFfVev3agkQjbgxsFtf04A7/2S+HtrLITZ83gLsUonGAZeRA9hy4xzeUb3WlGSBDo5+o4CK0+qmEWmAn4lLwrxizHkjjID4xFqBIWvLYciunZPgyAO1NeNr2GQ8mUHoHv5E1ikYTwrjrzU4KmfB8FKzPpCRsG8VC0QXiMRfByZ2avXEHSt7SrHfnoLDnnzjOvJAWn2U+0wOQBAfqIWCf1S5XiSAzfI4iF1ZzFZAyxF2ocXI4FQAZOJjAUI2qX4xFtNPyMonGqCtB4vbeCXdSLmQAR/Q7EWUsiRETkkORAH7bVpiiZAlSRK8xlrSePleZY7ZID81/tkCA5A4UQCXW/OyUUiSzb1WvQBO7Oo/Ri4yY/Jz90yIqVGllOP8t035saUE0WMPqVAH9igHYVHD/1VqL4UOK0mvrTrkEdk9870jexHnQn8jDmgegsRzhlxJd7DAKCSmwK31iEbiJCt3VSC5L9f4G3UE0Se346C2PDbB//ghLtfc2CkjnCpkdcKT8jdk3MReFi6Ls390SuiwXztvR7zW9fFcl62lY5VbN0edVStGWiIcT168qNVNEHWUm0fbiyqiVjLHtG4etKiTgt7yTGn8vn4SpYR1h3aM3lnbU2Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
